#!/usr/bin/env bash
set -euo pipefail

mojo_bin="${MOJO_BIN:-mojo}"
tests=(
  test_json.mojo
  test_botcommand.mojo
  test_bot.mojo
  test_string_models.mojo
  test_webappinfo.mojo
  test_webhookinfo.mojo
  test_menubutton.mojo
  test_update_parsing.mojo
  test_filters.mojo
  test_filter_factories.mojo
  test_basehandler.mojo
  test_pollhandler.mojo
  test_simple_update_handlers.mojo
  test_business_handlers.mojo
  test_paidmediapurchasedhandler.mojo
  test_managedbotupdatedhandler.mojo
  test_chatjoinrequesthandler.mojo
  test_chatmemberhandler.mojo
  test_chatboosthandler.mojo
  test_choseninlineresulthandler.mojo
  test_inlinequeryhandler.mojo
  test_prefixhandler.mojo
  test_messagereactionhandler.mojo
  test_commandhandler.mojo
  test_messagehandler.mojo
  test_typehandler.mojo
  test_trackingdict.mojo
  test_passportfile.mojo
  test_passportdata.mojo
  test_encryptedpassportelement.mojo
  test_passportdata_model.mojo
  test_passportelementerrors.mojo
  test_stringcommandhandler.mojo
  test_update.mojo
  test_cli_version.mojo
  test_dice.mojo
  test_scalar_models.mojo
  test_scalar_payment_models.mojo
  test_shippingoption.mojo
  test_paymentqueries.mojo
  test_successfulpayment.mojo
  test_revenuewithdrawalstate.mojo
  test_startransactions.mojo
  test_inputcontactcontent.mojo
  test_inputvenuemessagecontent.mojo
  test_inputinvoicemessagecontent.mojo
  test_timedelta.mojo
  test_datetime.mojo
  test_inputlocationmessagecontent.mojo
  test_inputtextmessagecontent.mojo
  test_messageautodeletetimerchanged.mojo
  test_messagereactionupdated.mojo
  test_location.mojo
  test_chatlocation.mojo
  test_venue.mojo
  test_photosize.mojo
  test_videoquality.mojo
  test_basemedium.mojo
  test_basethumbedmedium.mojo
  test_videochat.mojo
  test_document.mojo
  test_voice.mojo
  test_audio.mojo
  test_animation.mojo
  test_videonote.mojo
  test_video.mojo
  test_chatphoto.mojo
  test_livephoto.mojo
  test_maskposition.mojo
  test_forcereply.mojo
  test_keyboardbuttonrequestchat.mojo
  test_keyboardbutton.mojo
  test_replykeyboardmarkup.mojo
  test_inlinequeryresultsbutton.mojo
  test_inlinekeyboardbutton.mojo
  test_inlinekeyboardmarkup.mojo
  test_shared.mojo
  test_inlinequeryresultgame.mojo
  test_inlinequery.mojo
  test_inlinequeryresultcachedsticker.mojo
  test_inlinequeryresultcachedaudio.mojo
  test_inlinequeryresultcachedvoice.mojo
  test_inlinequeryresultcacheddocument.mojo
  test_inlinequeryresultcachedgif.mojo
  test_inlinequeryresultcachedmpeg4gif.mojo
  test_inlinequeryresultcachedphoto.mojo
  test_inlinequeryresultcachedvideo.mojo
  test_inlinequeryresultaudio.mojo
  test_inlinequeryresultvoice.mojo
  test_inlinequeryresultphoto.mojo
  test_inlinequeryresultdocument.mojo
  test_inlinequeryresultvideo.mojo
  test_inlinequeryresultgif.mojo
  test_inlinequeryresultmpeg4gif.mojo
  test_inlinequeryresultarticle.mojo
  test_inlinequeryresultcontact.mojo
  test_inlinequeryresultvenue.mojo
  test_inlinequeryresultlocation.mojo
  test_user.mojo
  test_chat.mojo
  test_callbackquery.mojo
  test_chatmember.mojo
  test_chatmemberupdated.mojo
  test_chatfullinfo.mojo
  test_chatinvitelink.mojo
  test_chatjoinrequest.mojo
  test_preparedinlinemessage.mojo
  test_managedbot.mojo
  test_affiliateinfo.mojo
  test_botaccesssettings.mojo
  test_user_related_models.mojo
  test_userprofiles.mojo
  test_file_model.mojo
  test_connected_models.mojo
  test_sticker.mojo
  test_optional_models.mojo
  test_nullable_scalar_models.mojo
  test_business_opening_hours.mojo
  test_business_models.mojo
  test_chatbackground.mojo
  test_birthdate.mojo
  test_error.mojo
  test_linkpreviewoptions.mojo
  test_repr.mojo
  test_argumentparsing.mojo
  test_transactionpartner.mojo
  test_transactionpartner_variants.mojo
  test_gift.mojo
  test_paidmedia.mojo
  test_uniquegift.mojo
  test_ownedgift.mojo
  test_story.mojo
  test_storyarea.mojo
  test_reply.mojo
  test_externalreplyinfo.mojo
  test_messageorigin.mojo
  test_pollanswer.mojo
  test_pollmedia.mojo
  test_polloption.mojo
  test_poll.mojo
  test_inputpolloption.mojo
  test_polloptionevents.mojo
  test_checklists.mojo
  test_game.mojo
  test_giveaway.mojo
  test_giveawaycompleted.mojo
  test_reaction.mojo
  test_inputfile.mojo
  test_file_helpers.mojo
  test_inputsticker.mojo
  test_inputchecklist.mojo
  test_inputprofilephoto.mojo
  test_inputstorycontent.mojo
  test_inputmedia.mojo
  test_markup.mojo
  test_contact.mojo
  test_small_models.mojo
  test_requestdata.mojo
  test_httpxrequest.mojo
  test_requestresponse.mojo
  test_helpers.mojo
  test_usernames.mojo
  test_entity_slicing.mojo
  test_entities.mojo
  test_botcommandscope.mojo
  test_messageid.mojo
  test_message.mojo
  test_messageentity.mojo
  test_translation_basics.mojo
  test_constants.mojo
  test_constants_data.mojo
  test_strings_data.mojo
  test_unicode_strings.mojo
)

for test_file in "${tests[@]}"; do
  printf 'Running %s\n' "$test_file"
  "$mojo_bin" run -O 0 -I src "tests/$test_file"
done
